### ISSUE TITLE
reverse initiative when sort combatants off

### ISSUE THREAD

**Issue by MrPotatoZed** [arcanistzed/ctg#10]
### Expected Behavior

Highest initiative roll should appear first in initiative order.

### Current Behavior

When sort combatants is off and selection method is active tokens are sorted in reverse initiative order with the lowest roll first. Advancing via next turn seems to move in correct order (highest roll first) despite the reverse order displayed in the tracker. Turning sort combatants on fixes the issue. No errors in console.
![image](https://user-images.githubusercontent.com/85974617/158917288-005c8b35-328b-4c50-a244-1cc43b707a94.png)

### Steps to Reproduce

See above.

### Version

1.0.0 RC1

### Foundry VTT Version

9.255

### Operating System

Windows

### Browser / App

Chrome, Firefox

### Game System

5e 1.5.7

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Fixed in v1.1.0
