### ISSUE TITLE
Roll a single value and set it as the Initiative of all the group

### ISSUE THREAD

**Issue by rpganalyst** [arcanistzed/ctg#12]
### Problem

I pass a lot of time in the first round of combat setting all the tokens of the same kind to the same Initiative value (dnd 5e standard ruling).

### Solution

I'd like to roll for a single initiative value and then have the entire group set it as initiative value.

**Comment by arcanistzed** [comment]
You can already do that. See the README for details: https://github.com/arcanistzed/ctg#rolling-group-initiative
