### ISSUE TITLE
[Bug]: There's a warning that ctg still uses v9 style data access

### ISSUE THREAD

**Issue by wickermoon** [arcanistzed/ctg#31]
### Expected Behavior

no error-warning

### Current Behavior

error-warning

### Steps to Reproduce

load up a world with ctg active

### Context

I already have a PR going on to fix it, it's a super easy fix.

### Version

1.4.3

### Foundry VTT Version

v10.284

### Operating System

Windows 10

### Browser / App

Native Electron App, Chrome

### Game System

dnd5e (2.0.2)

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Thanks for the PR! I will have to close it for now because I'd like to preserve v9 compatibility until at least v11 comes out.
